---
title: "iteration_and_listcols"
author: "Longyi Zhao"
date: "2023-10-31"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6, 
  out.width = "90%"
)

theme_set (theme_minimal() +theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplots.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_disrete = scale_fill_viridis_d
```

output on this page is fixed 
```{r}
set.seed(12345)
```

### List
```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)

tibble(
  num = vec_numeric,
    char = vec_char
)
```

different stuff with different length: not gonna work

```{r}
l = list(
  vec_numeric = 1:5, 
  vec_char = LETTERS, 
  matrix = matrix(1:10, nrow = 5, ncol = 2),
  summary = summary (rnorm(100))
)
```

accessing lists
```{r}
l$vec_char
l[[2]]
l[["summary"]]
```

## for loops
```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```

```{r}
mean_and_sd = function(x) {
   z = (x-mean(x))/sd(x)
  if (!is.numeric(x)) {
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z score")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x, 
    sd = sd_x
  )
  
}
```

```{r}
mean_and_sd(list_norms$a)
mean_and_sd(list_norms$b)
mean_and_sd(list_norms$c)
mean_and_sd(list_norms$d)
```

write a for loop
```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

## Use 'map'
use a map function to do the same thing
```{r}
output_map = map(list_norms, mean_and_sd)

output_median = map(list_norms, median)
```

##create a dataframe
```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"), 
    samp = list_norms
  )
```

```{r}
listcol_df |> pull(samp)
```

```{r}
mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[2]])
mean_and_sd(listcol_df$samp[[3]])
mean_and_sd(listcol_df$samp[[4]])
```

```{r}
map(listcol_df$samp, mean_and_sd)

# add a mean and sd column 
listcol_df |>
  mutate(mean_sd = map(samp, mean_and_sd),
         median = map(samp, median)) |>
  pull(mean_sd)
```

```{r}
listcol_df |>
  mutate(mean_sd = map(samp, mean_and_sd),
         median = map(samp, median)) |>
  select(mean_sd, name)
```

## NSDUH








